apiVersion: apps/v1
kind: Deployment
metadata:
  name: langchain-dep
  labels:
    app: langchain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langchain
  template:
    metadata:
      labels:
        app: langchain
    spec:
      containers:
      - name: langchain-container
        image: alstjrdlep/langchain:10
        ports:
        - containerPort: 5000
