apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: kube-system
  labels:
    k8s-app: fluent-bit-logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE filter-error-only.conf
    @INCLUDE output-elasticsearch.conf
    @INCLUDE output-s3.conf

  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            cri
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     30MB
        Skip_Long_Lines   On
        Refresh_Interval  10
        Read_from_Head    On

  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        #Kube_Tag_Prefix     kube.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off

  filter-error-only.conf: |
    #[FILTER]
    #Name      grep
    #Match     kube.*
    #Regex     message ERROR
    [FILTER]
        Name          rewrite_tag
        Match         kube.*
        Rule          $message ^.*ERROR.*$ error.$TAG false
    [FILTER]
        Name          rewrite_tag
        Match         kube.*
        Rule          $message ^.*status=500.*$ error.$TAG false


  output-elasticsearch.conf: |
    [OUTPUT]
        Name            es
        Match           error.*
        Host            elasticsearch-svc.default.svc.cluster.local
        Port            9200
        Logstash_Format On
        Logstash_Prefix fluent-bit
        Type            _doc
        Retry_Limit     False
        Generate_ID     On
        Write_Operation upsert

  output-s3.conf: |
    [OUTPUT]
        Name               s3
        Match              error.*
        bucket             engking-log-bucket
        region             ap-northeast-1
        total_file_size    1M
        upload_timeout     5m
        use_put_object     On
        s3_key_format      /logs/$TAG/%Y-%m-%d/%H-%M-%S-$UUID.json
        s3_key_format_tag_delimiters ._

  parsers.conf: |
    [PARSER]
        Name        cri
        Format      regex
        Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z

    [PARSER]
        Name   json
        Format json
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
